
name: Render
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render_api_key: ${{ secrets.RENDER_API_KEY }}
          render-app_name: ${{ secrets.RENDER_APP_NAME }}
          email: ${{ secrets.RENDER_EMAIL }}
          retries: 20
          wait: 16000
          sleep: 30000