name: Render Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker environment
      uses: docker/setup-docker@v1

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: BostonHousePricing/Dockerfile:${{ env.GITHUB_SHA }}

    - name: Deploy to Render
      uses: render-examples/render-github-actions@v1
      with:
        environment_variables:
          IMAGE: BostonHousePricing/Dockerfile:${{ env.GITHUB_SHA }}
        api_key: ${{ secrets.RENDER_API_KEY }}
 
 